# <img src="https://img.icons8.com/bubbles/100/000000/3d-glasses.png" style="height:50px;display:inline"> EE 046746 - Technion - Computer Vision


## Homework 4 - Structure From Motion
---

### <a style='color:red'> Due Date: 25.8.2024 </a>

### <img src="https://img.icons8.com/bubbles/50/000000/upload-to-cloud.png" style="height:50px;display:inline"> Submission Guidelines
---
#### READ THIS CAREFULLY
* Submission only in **pairs**.
* **No handwritten submissions**.
* You can choose your working environment:
    * You can work in a `Jupyter Notebook`, locally with <a href="https://www.anaconda.com/distribution/">Anaconda</a> or online on <a href="https://colab.research.google.com/">Google Colab</a>
  * **Important**: Colab also supports running code on GPU, so if you don't have one, Colab is the way to go. To enable GPU on Colab, in the menu: `Runtime` $\rightarrow$  `Change Runtime Type` $\rightarrow$`GPU`.
    * You can work in a Python IDE such as <a href="https://www.jetbrains.com/pycharm/">PyCharm</a> or <a href="https://code.visualstudio.com/">Visual Studio Code</a>.
        * Both also allow opening/editing Jupyter Notebooks.

* Make sure you submit your exercise according to the requirements in the <a href="https://moodle.technion.ac.il/pluginfile.php/1823033/mod_resource/content/2/Homework%20guidelines.pdf">"Homework submission guidelines"</a> file that appears in the course website (Moodle). 
            * **The code should run both on CPU and GPU without manual modifications**, require no special preparation and run on every computer.
* Be precise, we expect on point answers.
* Submission on the course website (Moodle).

### <img src="https://img.icons8.com/dusk/64/000000/python.png" style="height:50px;display:inline"> Python Libraries
---

* `numpy`
* `matplotlib`
* `opencv` (or `scikit-image`)
* `scikit-learn`
* `scipy`
* Anything else you need (`os`, `pandas`, `csv`, `json`,...)

In [70]:
!pip install tk
!pip install PyQt5
!pip install PySide2

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Defaulting to user installation because normal site-packages is not writeable


ERROR: Could not find a version that satisfies the requirement PySide2 (from versions: none)
ERROR: No matching distribution found for PySide2

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [71]:
import cv2 as cv
import numpy as np
import scipy.optimize
import numpy.linalg as la
import matplotlib.pyplot as plt

# for visualization windows to pop out in jupyter (kernel may require restart after using GUIs)
%matplotlib qt

### <img src="https://img.icons8.com/bubbles/50/000000/checklist.png" style="height:50px;display:inline"> Tasks
---
* In all tasks, you should document your process and results in a report file (which will be saved as `.pdf`). 
* You can reference your code in the report file, but no need for actual code in this file, the code is submitted in a seprate folder as explained above.

### <img src="https://img.icons8.com/external-itim2101-lineal-color-itim2101/64/000000/external-robot-engineering-itim2101-lineal-color-itim2101.png" style="height:50px;display:inline"> Introduction 
---
One of the major areas of computer vision is 3D reconstruction. Given several 2D images of an environment, can we recover the 3D structure of the environment, as well as the position of the camera/robot? This has many uses in robotics and autonomous systems, as understanding the 3D structure of the environment is crucial to navigation. You don't want your robot constantly bumping into walls, or running over human beings!

<center> <img src="https://research.qut.edu.au/qcr/wp-content/uploads/sites/305/2021/02/Challenge_summary_pic-768x513.jpg" style="height:300px">
<center> Image Source - <a href="https://research.qut.edu.au/qcr/2021/02/17/2nd-robotic-vision-scene-understanding-challenge-launched-cvpr2021-embodied-ai-workshop/"> CVPR 21 Embodied AI Workshop </a>

In Part 1, you will be writing a set of functions to generate a sparse point cloud for some test images we have provided to you. The test images are 2 renderings of a temple from two different angles. We have also provided you with a `npz` file containing good point correspondences between the two images. You will first write a function that computes the fundamental matrix between the two images. Then write a function that uses the epipolar constraint to find more point matches between the two images. Finally, you will write a function that will triangulate the 3D points for each pair of 2D point correspondences.

In Part 2, you will be writing a set of functions to calibrate a camera and project a 3D CAD model to a 2D image after estimating the camera pose. We have provided you with a `npz` file containing corresponding 2D-3D pairs. You will first write a function that estimates a camera matrix given 2D-3D calibration points. Then write a function to decompose the estimated camera matrix to intrinsic/extrinsic parameters. Finally, you will write a script to project the provided 3D CAD model and compare it to a given 2D image of an airplane.

### <img src="https://img.icons8.com/pastel-glyph/64/000000/pain-points.png" style="height:50px;display:inline"> Part 1 - Sparse Reconstruction 
---
In this section, you will be writing a set of function to compute the sparse reconstruction from two sample images of a temple. You will first estimate the Fundamental matrix, compute point correspondences, then plot the results in 3D.
It may be helpful to read through Section 1.5 right now. In Section 1.5 we ask you to write a testing script that will run your whole pipeline. It will be easier to start that now and add to it as you complete each of the questions one after the other.

#### 1.1 - Eight Point Algorithm
---
In this question, you're going to use the eight point algorithm which is covered in class to estimate the fundamental matrix. Please use the point correspondences provided in `data/some_corresp.npz`; you can load and view the contents of a `.npz` file as follows:
> ``data = np.load("./Users/yiftachedelstain/ee046746-computer-vision-private/HW/hw4_structure_from_motion/data/some_corresp.npz")``
<br> `` print(data.files)`` </br>

* Write the following function:

In [72]:
def eight_point(pts1, pts2, pmax):
    """
    Eight Point Algorithm
    [I] pts1, points in image 1 (Nx2 matrix)
        pts2, points in image 2 (Nx2 matrix)
        pmax, scalar value computed as max(H1,W1)
    [O] F, the fundamental matrix (3x3 matrix)
    """
    # replace pass by your implementation

    # Define the normalization matrix
    T = np.array([[1/pmax, 0, 0],
                  [0, 1/pmax, 0],
                  [0, 0, 1]])

    # Construct the A matrix
    normalized_pts1 = np.array([(T @ np.append(pt, 1))[:2] for pt in pts1])
    normalized_pts2 = np.array([(T @ np.append(pt, 1))[:2] for pt in pts2])
    A = np.zeros((pts1.shape[0], 9))
    for i in range(pts1.shape[0]):
        x1, y1 = normalized_pts1[i]
        x2, y2 = normalized_pts2[i]
        A[i] = [x2*x1, x1*y2, x1, y1*x2, y1*y2, y1, x2, y2, 1]

    # Solve for the fundamental matrix
    _, _, V = la.svd(A)
    F = V[-1].reshape(3,3)

    # Enforce rank 2 constraint
    F = refineF(F, normalized_pts1, normalized_pts2)
    return T.T @ F @ T

where `pts1` and `pts2` are $N \times 2$ matrices corresponding to the $(x,y)$ coordinates of the $N$ points in the first and second image respectively, and `pmax` is a scale parameter. Implementation tips:
* Normalize points and un-normalize $F$: You should scale the data by dividing each coordinate by $p_{\text{max}}$ (the maximum of the image's width and height) using a transformation matrix $T$. After computing $F$, you will have to "unscale" the fundamental matrix. If $p_{\text{norm}} = Tp$, then $F_{\text{unnorm}} = T^T F T$. Note that this scaling is slightly simpler than "centering" that you did in the lecture, but for the purpose of this assingment it should suffice.

* You must enforce the rank 2 constraint on $F$ before unscaling. Recall that a valid fundamental matrix $F$ will have all epipolar lines intersect at a certain point, meaning that there exists a non-trivial null space for $F$. In general, with real points, the eight-point solution for $F$ will not come with this condition. To enforce the rank 2 constraint, decompose $F$ with SVD to get the three matrices $U,\Sigma,V$ such that $F = U\Sigma V^T$. Then force the matrix to be rank 2 by setting the smallest singular value in $\Sigma$ to zero, giving you a new $\Sigma'$. Now compute the proper fundamental matrix with $F' = U\Sigma' V^T$.

* You may find it helpful to refine the solution by using local minimization. This probably won't fix a completely broken solution, but may make a good solution better by locally minimizing a geometric cost function. For this we have provided a helper function `refineF` taking in $F$ and the two sets of points, which you can call from `eight_point` before unscaling $F$.

* Remember that the x-coordinate of a point in the image is its column entry and y-coordinate is the row entry. Also note that eight-point is just a "figurative" name, it just means that you need at least 8 points; your algorithm should use an over-determined system ($N > 8$ points).

* To visualize the correctness of your estimated $F$, use the provided function `displayEpipolarF`, which takes in $F$, and the two images. This GUI lets you select a point in one of the images and visualize the corresponding epipolar line in the other image (Figure 1).

*  Please include in your report the recovered $F$ and the visualization of some epipolar lines (similar to Figure 1).

* Helper functions:

In [73]:
# helper function 1: singualrizes F using SVD
def _singularize(F):
    U, S, V = np.linalg.svd(F)
    S[-1] = 0
    F = U.dot(np.diag(S).dot(V))

    return F

# helper function 2.1: defines an objective function using F and the epipolar constraint
def _objective_F(f, pts1, pts2):
    F = _singularize(f.reshape([3, 3]))
    num_points = pts1.shape[0]
    hpts1 = np.concatenate([pts1, np.ones([num_points, 1])], axis=1)
    hpts2 = np.concatenate([pts2, np.ones([num_points, 1])], axis=1)
    Fp1 = F.dot(hpts1.T)
    FTp2 = F.T.dot(hpts2.T)

    r = 0
    for fp1, fp2, hp2 in zip(Fp1.T, FTp2.T, hpts2):
        r += (hp2.dot(fp1))**2 * (1/(fp1[0]**2 + fp1[1]**2) + 1/(fp2[0]**2 + fp2[1]**2))

    return r

# helper function 2.2: refines F using the objective from above and local optimization
def refineF(F, pts1, pts2):
    f = scipy.optimize.fmin_powell(
        lambda x: _objective_F(x, pts1, pts2), F.reshape([-1]),
        maxiter=100000,
        maxfun=10000
    )

    return _singularize(f.reshape([3, 3]))

* Visualization functions:

In [74]:
# helper function 3.1: derives the epipoles using the essential matrix
def _epipoles(E):
    U, S, V = np.linalg.svd(E)
    e1 = V[-1, :]
    U, S, V = np.linalg.svd(E.T)
    e2 = V[-1, :]

    return e1, e2

# helper function 3.2: GUI that uses F to draw the epipolar lines in I2 correponding to chosen pts in I1
def displayEpipolarF(I1, I2, F):
    e1, e2 = _epipoles(F)

    sy, sx, _ = I2.shape

    f, [ax1, ax2] = plt.subplots(1, 2, figsize=(12, 9))
    ax1.imshow(I1)
    ax1.set_title('Select a point in this image')
    ax1.set_axis_off()
    ax2.imshow(I2)
    ax2.set_title('Verify that the corresponding point \n is on the epipolar line in this image')
    ax2.set_axis_off()

    while True:
        plt.sca(ax1)
        x, y = plt.ginput(1, mouse_stop=2)[0]

        xc, yc = int(x), int(y)
        v = np.array([[xc], [yc], [1]])

        l = F @ v
        s = np.sqrt(l[0]**2+l[1]**2)

        if s==0:
            error('Zero line vector in displayEpipolar')

        l = l / s
        if l[1] != 0:
            xs = 0
            xe = sx - 1
            ys = -(l[0] * xs + l[2]) / l[1]
            ye = -(l[0] * xe + l[2]) / l[1]
        else:
            ys = 0
            ye = sy - 1
            xs = -(l[1] * ys + l[2]) / l[0]
            xe = -(l[1] * ye + l[2]) / l[0]

        ax1.plot(x, y, '*', linewidth=2) # changed from MarkerSize to markersize
        ax2.plot([xs, xe], [ys, ye], linewidth=2)
        plt.draw()

* Example result:

<center> <img src = "../assets/displayEpipolarF_example.jpg" style="width:75%">
<center> Figure 1 - Epipolar lines visualization from "displayEpipolarF"

In [75]:
data = np.load('../data/some_corresp.npz')
print(data.files)

['pts1', 'pts2']


In [76]:
pts1, pts2 = data['pts1'], data['pts2']
im1 = cv.cvtColor(cv.imread('../data/im1.png'), cv.COLOR_BGR2RGB)
im2 = cv.cvtColor(cv.imread('../data/im2.png'), cv.COLOR_BGR2RGB)
p_max = max(im1.shape[0], im1.shape[1])
F = eight_point(pts1, pts2, p_max)
print("Fundamental Matrix: \n", F)

Optimization terminated successfully.
         Current function value: 0.000106
         Iterations: 55
         Function evaluations: 5545
Fundamental Matrix: 
 [[-1.59040538e-09  1.20994612e-07 -2.86915213e-06]
 [ 6.79859772e-08  4.68517026e-11 -1.13237809e-03]
 [-1.61329333e-05  1.08910347e-03  4.44256021e-03]]


In [77]:
displayEpipolarF(im1, im2, F)

IndexError: list index out of range

#### 1.2 - Epipolar Correpondences
---
To reconstruct a 3D scene with a pair of two images, we need to find many point pairs. A point pair is two points (one in each image) that correspond to the same 3D scene point. With enough of these pairs, when we plot the resulting 3D points, we will have a rough outline of the 3D object. You found point pairs in HW1 using feature detectors and feature descriptors, and testing a point in one image with every single point in the other image. But here we can use the fundamental matrix to greatly simplify this search.

<center> <img src = "../assets/epipolar_theory.jpg" style="width:50%">
<center> Figure 2 - Epipolar Geometry. Potential matches for $p$ lie on the epipolar line $l'$.

Recall from class that given a point $p$ in one image (the left view in Figure 2). Its corresponding 3D scene point $P$ could lie anywhere along the line from the camera center $C$ to the point $p$. This line, along with a second image's camera center $C'$ (the right view in Figure 2) forms a plane. This plane intersects with the image plane of the second camera, resulting in a line $l'$ in the second image which describes all the possible locations that $p$ may be found in the second image. Line $l'$ is the epipolar line, and we only need to search along this line to find a match for point $p$ found in the first image.

* Write the following function:

In [78]:
def epipolar_correspondences(I1, I2, F, pts1):
    """
    Epipolar Correspondences
    [I] I1, image 1 (H1xW1 matrix)
        I2, image 2 (H2xW2 matrix)
        F, fundamental matrix from image 1 to image 2 (3x3 matrix)
        pts1, points in image 1 (Nx2 matrix)
    [O] pts2, points in image 2 (Nx2 matrix)
    """
    window_radius = 10  # Half of the window size
    matches = []

    # Iterate over each point in the first image
    for pt in pts1:
        x1, y1 = pt
        # Define a search window around the point in the first image
        patch1 = I1[max(0, y1 - window_radius):y1 + window_radius + 1,
                    max(0, x1 - window_radius):x1 + window_radius + 1]

        # Compute the corresponding epipolar line in the second image
        line = F @ np.array([x1, y1, 1])
        a, b, c = line

        # Initialize variables to track the best match
        best_match = None
        lowest_distance = float('inf')

        # Search along the epipolar line in the second image
        for x2 in range(I2.shape[1]):
            # Calculate the y-coordinate on the epipolar line
            if b != 0:
                y2 = int(-(a * x2 + c) / b)
            else:
                continue

            # Ensure y2 is within image bounds
            if 0 <= y2 < I2.shape[0]:
                # Extract a patch from the second image
                patch2 = I2[max(0, y2 - window_radius):y2 + window_radius + 1,
                            max(0, x2 - window_radius):x2 + window_radius + 1]

                # Compare patch sizes before calculating distance
                if patch1.shape == patch2.shape:
                    # Compute the Euclidean distance between patches
                    distance = np.linalg.norm(patch1.astype(np.int32) - patch2.astype(np.int32))
                    # Update the best match if a smaller distance is found
                    if distance < lowest_distance:
                        lowest_distance = distance
                        best_match = (x2, y2)

        # Append the best match to the list of corresponding points
        matches.append(best_match)

    return np.array(matches)

In [79]:
epipolar_correspondences(im1, im2, F, pts1)

array([[259, 158],
       [280, 311],
       [202, 157],
       [334, 150],
       [311, 198],
       [269, 304],
       [331, 160],
       [141, 158],
       [348, 237],
       [260, 241],
       [351, 260],
       [271, 194],
       [332, 189],
       [189, 202],
       [280, 253],
       [269, 161],
       [290, 222],
       [326, 133],
       [305, 157],
       [388, 485],
       [171, 263],
       [263, 149],
       [372, 306],
       [197, 150],
       [202, 152],
       [279, 255],
       [157, 193],
       [404, 458],
       [230, 161],
       [362, 192],
       [367, 293],
       [349, 404],
       [269, 362],
       [349, 234],
       [134, 485],
       [195, 255],
       [276, 266],
       [172, 265],
       [104, 471],
       [143, 162],
       [151, 199],
       [261, 195],
       [337, 161],
       [211, 145],
       [278, 381],
       [309, 228],
       [134, 147],
       [138, 153],
       [257, 238],
       [309, 225],
       [214, 409],
       [174, 196],
       [292,

where `I1` and `I2` are two-view images, `F` is the fundamental matrix computed for the two images using your `eight_point` function, `pts1` is a $N \times 2$ matrix containing the $(x,y)$ points in the first image, and the function should return `pts2`, a $N \times 2$ matrix, which contains the corresponding points in the second image. Implementation tips:

* To match one point $p$ in image 1, use the fundamental matrix to estimate the corresponding epipolar line $l'$ and generate a set of candidate points in the second image.

* For each candidate points $p'$, a similarity score between $p$ and $p'$ is computed. The point among candidates with highest score is treated as epipolar correspondence.

* There are many ways to define the similarity between two points. Feel free to use whatever you want and **describe it in your write-up**. One possible solution is to select a small window of size $w$ around the point $p$. Then compare this target window to the window of the candidate point in the second image. For the images we gave you, simple Euclidean distance or Manhattan distance should suffice.

* Remember to take care of data type and index range. You can use the provided function `epipolarMatchGUI` to visually test your function. Your function does not need to be perfect, but it should get most easy points correct, like corners, dots etc.

* Please include a screenshot of `epipolarMatchGUI` running with your implementation of `epipolar_correspondences` (similar to Figure 3). Mention the similarity metric you decided to use. Also comment on any cases where your matching algorithm consistently fails, and why you might think this is.

* Visualization function:

In [80]:
# helper function 4: GUI that uses F, and the matching function to draw the epipolar correpondences on the epipolar lines
def epipolarMatchGUI(I1, I2, F):
    e1, e2 = _epipoles(F)

    sy, sx, sd = I2.shape

    f, [ax1, ax2] = plt.subplots(1, 2, figsize=(12, 9))
    ax1.imshow(I1)
    ax1.set_title('Select a point in this image')
    ax1.set_axis_off()
    ax2.imshow(I2)
    ax2.set_title('Verify that the corresponding point \n is on the epipolar line in this image')
    ax2.set_axis_off()

    while True:
        plt.sca(ax1)
        x, y = plt.ginput(1, mouse_stop=2)[0]

        xc, yc = int(x), int(y)
        v = np.array([[xc], [yc], [1]])

        l = F @ v
        s = np.sqrt(l[0]**2+l[1]**2)

        if s==0:
            error('Zero line vector in displayEpipolar')

        l = l / s
        if l[0] != 0:
            xs = 0
            xe = sx - 1
            ys = -(l[0] * xs + l[2]) / l[1]
            ye = -(l[0] * xe + l[2]) / l[1]
        else:
            ys = 0
            ye = sy - 1
            xs = -(l[1] * ys + l[2]) / l[0]
            xe = -(l[1] * ye + l[2]) / l[0]

        ax1.plot(x, y, '*', linewidth=2)
        ax2.plot([xs, xe], [ys, ye], linewidth=2)

        # draw points
        pc = np.array([[xc, yc]])
        p2 = epipolar_correspondences(I1, I2, F, pc)
        ax2.plot(p2[0,0], p2[0,1], 'ro', linewidth=2)
        plt.draw()

* Example result:

<center> <img src = "../assets/epipolarMatchGUI_example.jpg" style="width:75%">
<center> Figure 3 - Epipolar Match visualization. A few errors are alright, but it should get most easy points correct (corners, dots, etc.)

In [82]:
epipolarMatchGUI(im1, im2, F)

KeyboardInterrupt: 

#### 1.3 - Essential Matrix
---
In order to get the full camera projection matrices we need to compute the Essential matrix. So far, we have only been using the Fundamental matrix.

* Write the following function:

In [83]:
def essential_matrix(F, K1, K2):
    """
    Essential Matrix
    [I] F, the fundamental matrix (3x3 matrix)
        K1, camera matrix 1 (3x3 matrix)
        K2, camera matrix 2 (3x3 matrix)
    [O] E, the essential matrix (3x3 matrix)
    """
    
    E=  K2.T @ F @ K1
    return E

Where `F` is the Fundamental matrix computed between two images, `K1` and `K2` are the intrinsic camera matrices for the first and second image respectively (contained in `data/intrinsics.npz`), and `E` is the computed essential matrix. The intrinsic camera parameters are typically acquired through camera calibration. Refer to the class slides for the
relationship between the Fundamental matrix and the Essential matrix.

* Please include your estimated $E$ matrix for the temple image pair in the PDF report.

In [85]:
intrinsics_data = np.load("../data/intrinsics.npz")
K1, K2 = intrinsics_data['K1'], intrinsics_data['K2']
E = essential_matrix(F, K1, K2)
print("Essential Matrix: \n", E)

Essential Matrix: 
 [[-3.67640677e-03  2.80704882e-01  4.03209722e-02]
 [ 1.57725996e-01  1.09088137e-04 -1.69651547e+00]
 [ 2.58397439e-04  1.71769667e+00  1.97646825e-03]]


#### 1.4 - Triangulation
---
Write a function to triangulate pairs of 2D points in the images to a set of 3D points.

* Write the following function:

In [86]:
def choose_M2(M1, M2s, pts1, pts2):
    """
    Choose the appropriate M2 matrix according to the condition presented in the tutorial notebook.
    [I] M1, camera projection matrix 1 (3x4 matrix)
        M2s, camera projection matrices 2 (3x4x4 tensor)
        pts1, points in image 1 (Nx2 matrix)
        pts2, points in image 2 (Nx2 matrix)
    [O] M2, correct camera projection matrix (3x4 matrix)
    """
    max_visible_points = -1
    optimal_M2 = None
    for i in range(M2s.shape[2]):
        M2_candidate = M2s[:, :, i]
        reconstructed_points = triangulate(M1, pts1, M2_candidate, pts2)
        idx_to_exst = lambda idx: M2s[:, :, idx]
        transformation = idx_to_exst(i)
        transformed_points = np.dot(transformation, np.vstack((reconstructed_points.T, np.ones((1, reconstructed_points.shape[0]))))).T
        visible_points_count = np.count_nonzero(transformed_points[:, 2] > 0)

        if visible_points_count > max_visible_points:
            max_visible_points = visible_points_count
            optimal_M2 = M2_candidate

    return optimal_M2

def triangulate(M1, pts1, M2, pts2):
    """
    Triangulation
    [I] M1, camera projection matrix 1 (3x4 matrix)
        pts1, points in image 1 (Nx2 matrix)
        M2, camera projection matrix 2 (3x4 matrix)
        pts2, points in image 2 (Nx2 matrix)
    [O] pts3d, 3D points in space (Nx3 matrix)
    """
    three_d_points = []
    for point1, point2 in zip(pts1, pts2):
        x1, y1 = point1
        x2, y2 = point2
        A_matrix = np.array([
            y1 * M1[2, :] - M1[1, :],
            M1[0, :] - x1 * M1[2, :],
            y2 * M2[2, :] - M2[1, :],
            M2[0, :] - x2 * M2[2, :]
        ])
        _, _, Vt = np.linalg.svd(A_matrix)
        homogeneous_point = Vt[-1]
        point_3d = homogeneous_point[:3] / homogeneous_point[3]
        three_d_points.append(point_3d)
    return np.array(three_d_points)

Where `pts1` and `pts2` are the $N\times 2$ matrices with the 2D image coordinates, `M1` and `M2` are the $3\times4$ camera projection matrices and `pts3d` is an $N\times 3$ matrix with the corresponding 3D points (in all cases, one point per row). Remember that you will need to multiply the given intrinsic matrices with your solution for the extrinsic camera matrices to obtain the final camera projection matrices. 

* For `M1` you can assume no rotation or translation, so the extrinsic matrix is just $\left[I \lvert 0\right]$. 

* For `M2`, pass the essential matrix to the provided function `camera2` to get four possible **extrinsic** matrices. You will need to determine which of these is the correct one to use. Refer to the class slides to remind yourself of the 4 possible camera layouts. The correct configuration is the one for which most of the 3D points are in front of both cameras (i.e. have a positive depth), and make up a reasonable recovered shape. To make sure you choose the right one, write a helper function that apply the extrinsics of camera 2 to the recovered 3D points and check that they are still in front of camera 1 (positive $Z$).

* Keep in mind to multiply the extrinsics matrices by the corresponding intrinsics before inputting them to `triangulate`.
* Once implemented, check the performance by looking at the re-projection error. To compute the re-projection error, project the estimated 3D points back to the image 1 and compute the mean Euclidean error between projected 2D points and the given `pts1`.

* **In your write-up**: Describe how you determined which extrinsic matrix is correct. Note that simply rewording the hint is not enough. Report your re-projection error using the given `pts1` and `pts2` in `data/some_corresp.npz`. If implemented correctly, the re-projection error should be less than 2 pixels.

* Helper functions:

In [87]:
# helper function 5: returns the 4 options for camera matrix M2 given the essential matrix
def camera2(E):
    U,S,V = np.linalg.svd(E)
    m = S[:2].mean()
    E = U.dot(np.array([[m,0,0], [0,m,0], [0,0,0]])).dot(V)
    U,S,V = np.linalg.svd(E)
    W = np.array([[0,-1,0], [1,0,0], [0,0,1]])

    if np.linalg.det(U.dot(W).dot(V))<0:
        W = -W

    M2s = np.zeros([3,4,4])
    M2s[:,:,0] = np.concatenate([U.dot(W).dot(V), U[:,2].reshape([-1, 1])/abs(U[:,2]).max()], axis=1)
    M2s[:,:,1] = np.concatenate([U.dot(W).dot(V), -U[:,2].reshape([-1, 1])/abs(U[:,2]).max()], axis=1)
    M2s[:,:,2] = np.concatenate([U.dot(W.T).dot(V), U[:,2].reshape([-1, 1])/abs(U[:,2]).max()], axis=1)
    M2s[:,:,3] = np.concatenate([U.dot(W.T).dot(V), -U[:,2].reshape([-1, 1])/abs(U[:,2]).max()], axis=1)

    return M2s

In [88]:
# Initialize the first camera's extrinsic matrix
camera1_extrinsic = np.hstack((np.eye(3), np.zeros((3, 1))))
camera1_projection = K1 @ camera1_extrinsic

# Compute the essential matrix
essential_mat = essential_matrix(F, K1, K2)

# Generate candidate second camera matrices
candidate_M2s = camera2(essential_mat)

# Extract points from the dataset
image1_points, image2_points = data['pts1'], data['pts2']

# Select the correct extrinsic matrix for the second camera
optimal_M2_extrinsic = choose_M2(camera1_projection, candidate_M2s, image1_points, image2_points)

# Compute the second camera's projection matrix
camera2_projection = K2 @ optimal_M2_extrinsic

# Output the result
print("camera2_projection = ")
print(camera2_projection)

camera2_projection = 
[[ 1.39479171e+03 -3.54919778e+01  6.75507188e+02  1.47099461e+03]
 [-2.68068668e+01  1.52580437e+03  2.46004116e+02 -4.36825325e+00]
 [-2.51905111e-01  1.34124776e-03  9.67751009e-01 -1.63420852e-01]]


#### 1.5 - Putting It All Together
---
You now have all the pieces you need to generate a full 3D reconstruction. Write a test script `test_temple_coords` that does the following:

* Load the two images and the point correspondences from `data/some_corresp.npz`.
* Run eight point to compute the fundamental matrix `F`.
* Load the points in image 1 contained in `data/temple_coords.npz` and run your `epipolar_correspondences` on them to get the corresponding points in image 2.
* Load `data/intrinsics.npz` and compute the essential matrix `E`.
* Compute the first camera projection matrix `M1` and use `camera2` to compute the four candidates for `M2`.
* Run your `triangulate` function using the four sets of camera matrix candidates (after scaling with the intrinsics), the points from `data/temple_coords.npz`, and their computed correspondences.
* Figure out the correct `M2` and the corresponding 3D points.
* Use matplotlib's scatter function to plot these point correspondences on screen.
* Report your computed extrinsic parameters (`R1`,`R2`,`t1`,`t2`) in your PDF.
* We will use your test script to run your code, so be sure it runs smoothly. In particular, use relative paths to load files, not absolute paths.
* **In your write-up**: Include 3 images of your final reconstruction of the points given in the file `data/temple_coords.npz`, from different angles as shown in Figure 4.

* Example result:

<center> <img src = "/assets/pointcloud_example.jpg" style="width:75%">
<center> Figure 4 - Sample Reconstructions.

In [97]:
def test_temple_coords():
    im1 = cv.imread('temple1.png', cv.IMREAD_GRAYSCALE)
    im2 = cv.imread('temple2.png', cv.IMREAD_GRAYSCALE)


In [98]:
# Load correspondence data
correspondence_data = np.load("../data/some_corresp.npz")
image1_points, image2_points = correspondence_data['pts1'], correspondence_data['pts2']

# Load and convert images
first_image = cv.cvtColor(cv.imread("../data/im1.png"), cv.COLOR_BGR2RGB)
second_image = cv.cvtColor(cv.imread("../data/im2.png"), cv.COLOR_BGR2RGB)
max_dimension = np.max(first_image.shape)

# Compute fundamental matrix
fundamental_matrix = eight_point(image1_points, image2_points, max_dimension)

# Load temple coordinates and find epipolar correspondences
temple_data = np.load("../data/temple_coords.npz")
temple_points = temple_data['pts1']
corresponding_points = epipolar_correspondences(first_image, second_image, fundamental_matrix, temple_points)

# Load camera intrinsics
camera_intrinsics = np.load("../data/intrinsics.npz")
intrinsic1, intrinsic2 = camera_intrinsics['K1'], camera_intrinsics['K2']

# Compute essential matrix
essential_matrix_value = essential_matrix(fundamental_matrix, intrinsic1, intrinsic2)

# Set up camera projection matrices
camera1_extrinsic = np.hstack((np.eye(3), np.zeros((3, 1))))
projection1 = intrinsic1 @ camera1_extrinsic
extrinsic_candidates = camera2(essential_matrix_value)

# Prepare candidate projection matrices for the second camera
projection_candidates = np.zeros_like(extrinsic_candidates)
for i in range(extrinsic_candidates.shape[2]):
    projection_candidates[:, :, i] = intrinsic2 @ extrinsic_candidates[:, :, i]

# Define a function to extract extrinsics
extract_extrinsic = lambda idx: extrinsic_candidates[:, :, idx]

# Choose the correct second camera projection matrix
projection2 = choose_M2(projection1, projection_candidates, temple_points, corresponding_points)

# Perform triangulation to get 3D points
points_3d = triangulate(projection1, temple_points, projection2, corresponding_points)

# Plot the 3D points from different perspectives
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(points_3d[:, 0], points_3d[:, 1], points_3d[:, 2])
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.show()

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(points_3d[:, 1], points_3d[:, 2], points_3d[:, 0])
plt.show()

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(-points_3d[:, 2], -points_3d[:, 0], -points_3d[:, 1])
plt.show()

Optimization terminated successfully.
         Current function value: 0.000106
         Iterations: 55
         Function evaluations: 5545


### <img src="https://img.icons8.com/external-ddara-lineal-ddara/64/000000/external-yoga-pose-yoga-poses-ddara-lineal-ddara-36.png" style="height:50px;display:inline"> Part 2 - Pose Estimation (BONUS)
---
In this section, you will implement what you have learned in class to estimate the intrinsic and extrinsic parameters of camera given 2D points $p$ on image and their corresponding 3D points $P$. In other words, given a set of matched points $\left\{P_i ,p_i\right\}$ and camera model (in homogeneous coordinates):

$$ p = M P$$

we want to find the estimate of the camera matrix $M\in \mathbb{R}^{3\times4}$, as well as intrinsic parameter
matrix $K\in \mathbb{R}^{3\times3}$, camera rotation $R\in \mathbb{R}^{3\times3}$ and camera translation $t\in \mathbb{R}^{3\times1}$, such that:
$$ M = K \left[R \lvert t\right] $$

#### 2.1 - Estimating $M$ (BONUS)
---
* Write a function that estimates the camera matrix $M$ given 2D and 3D points $p,P$.

In [99]:
def estimate_pose(p, P):
    """
    Camera Matrix Estimation
    [I] p, 2D points (Nx2 matrix)
        P, 3D points (Nx3 matrix)
    [O] M, camera matrix (3x4 matrix)
    """
    num_points = p.shape[0]
    coefficient_matrix = np.zeros((2 * num_points, 12))

    for i in range(num_points):
        img_x, img_y = p[i]
        world_x, world_y, world_z = P[i]
        
        # Fill in the matrix rows for each point correspondence
        coefficient_matrix[2 * i] = [world_x, world_y, world_z, 1, 0, 0, 0, 0, -img_x * world_x, -img_x * world_y, -img_x * world_z, -img_x]
        coefficient_matrix[2 * i + 1] = [0, 0, 0, 0, world_x, world_y, world_z, 1, -img_y * world_x, -img_y * world_y, -img_y * world_z, -img_y]

    # Use SVD to solve for the projection matrix
    _, _, vh = np.linalg.svd(coefficient_matrix)
    projection_matrix = vh[-1].reshape(3, 4)

    return projection_matrix

where `p` is $2\times N$ matrix denoting the $(x, y)$ coordinates of the $N$ points on the image plane and `P` is $3\times N$ matrix denoting the $(x,y,z)$ coordinates of the corresponding points in the 3D world. Recall that this camera matrix can be computed using the same strategy as homography estimation by Direct Linear Transform (DLT).

* Once you finish this function, you can run the following script to test your implementation:

In [100]:
# 1. Generate random camera matrix
K = np.array([[1,0,100], [0,1,100], [0,0,1]])
R, _,_ = la.svd(np.random.randn(3,3))
if la.det(R) < 0: R = -R
t = np.vstack((np.random.randn(2,1), 1))
M = K @ np.hstack((R, t))

# 2. Generate random 2D and 3D points
N = 100
P = np.random.randn(N,3)
p = M @ np.hstack((P, np.ones((N,1)))).T
p = p[:2,:].T / np.vstack((p[2,:], p[2,:])).T

# 3. Test pose estimation with clean points
Mc = estimate_pose(p, P)
pp = Mc @ np.hstack((P, np.ones((N,1)))).T
pp = pp[:2,:].T / np.vstack((pp[2,:], pp[2,:])).T

print('Reprojection Error with clean 2D points:', la.norm(p-pp))
print('Pose Error with clean 2D points:', la.norm((Mc/Mc[-1,-1])-(M/M[-1,-1])))

# 4. Test pose estimation with noisy points
p = p + np.random.rand(p.shape[0], p.shape[1])
Mn = estimate_pose(p, P)
pp = Mn @ np.hstack((P, np.ones((N,1)))).T
pp = pp[:2,:].T / np.vstack((pp[2,:], pp[2,:])).T

print('Reprojection Error with noisy 2D points:', la.norm(p-pp))
print('Pose Error with noisy 2D points:', la.norm((Mn/Mn[-1,-1])-(M/M[-1,-1])))

Reprojection Error with clean 2D points: 4.1209736034627867e-10
Pose Error with clean 2D points: 4.866848470746969e-12
Reprojection Error with noisy 2D points: 10.280301348376694
Pose Error with noisy 2D points: 0.9338931821150536


* **In your write-up**: Please include the output of this script in your PDF.

#### 2.2 - Intrinsic/Extrinsic Parameters (BONUS)
---
* Write a function that estimates both intrinsic and extrinsic parameters from a camera matrix:

In [101]:
import scipy.linalg as la
import matplotlib.patches as patches

In [102]:
def estimate_params(M):
    """
    Camera Parameter Estimation
    [I] M, camera matrix (3x4 matrix)
    [O] K, camera intrinsics (3x3 matrix)
        R, camera extrinsics rotation (3x3 matrix)
        t, camera extrinsics translation (3x1 matrix)
    """
    # Calculate the camera center using the null space of the camera matrix
    _, _, Vt = la.svd(M)
    homogeneous_center = Vt[-1]
    camera_center = homogeneous_center[:3] / homogeneous_center[-1]

    # Use RQ decomposition from scipy.linalg to separate intrinsic and rotation matrices
    intrinsic_matrix, rotation_matrix = la.rq(M[:, :3])

    # Ensure that the diagonal of the intrinsic matrix is positive
    T = np.diag(np.sign(np.diag(intrinsic_matrix)))
    intrinsic_matrix = intrinsic_matrix @ T
    rotation_matrix = T @ rotation_matrix

    # Determine the translation vector
    translation_vector = -rotation_matrix @ camera_center

    return intrinsic_matrix, rotation_matrix, translation_vector

From what we learned on class, the `estimate_params` function should consecutively run the following steps:
* Compute the camera center $c$ by using SVD. Hint: $c$ is the eigenvector corresponding to the smallest eigenvalue.
* Compute the intrinsic $K$ and rotation $R$ by using QR decomposition. $K$ is a right upper triangle matrix while $R$ is an orthonormal matrix.
* Compute the translation by $t = -Rc$.

* Once you finish this function, you can run the following script to test your implementation:

In [107]:
# 1. Generate random camera matrix
K = np.array([[1,0,100], [0,1,100], [0,0,1]])
R, _,_ = la.svd(np.random.randn(3,3))
if la.det(R) < 0: R = -R
t = np.vstack((np.random.randn(2,1), 1))
M = K @ np.hstack((R, t))

# 2. Generate random 2D and 3D points
N = 100
P = np.random.randn(N,3)
p = M @ np.hstack((P, np.ones((N,1)))).T
p = p[:2,:].T / np.vstack((p[2,:], p[2,:])).T

# 3. Test parameter estimation with clean points
Mc = estimate_pose(p, P)
Kc, Rc, tc = estimate_params(Mc)

print('Intrinsic Error with clean 2D points:', la.norm((Kc/Kc[-1,-1])-(K/K[-1,-1])))
print('Rotation Error with clean 2D points:', la.norm(R-Rc))
print('Translation Error with clean 2D points:', la.norm(t-tc))

# 4. Test parameter estimation with noisy points
p = p + np.random.rand(p.shape[0], p.shape[1])
Mn = estimate_pose(p, P)
Kn, Rn, tn = estimate_params(Mn)

print('Intrinsic Error with noisy 2D points:', la.norm((Kn/Kn[-1,-1])-(K/K[-1,-1])))
print('Rotation Error with noisy 2D points:', la.norm(R-Rn))
print('Translation Error with noisy 2D points:', la.norm(t-tn))

Intrinsic Error with clean 2D points: 2.4817071013422765e-12
Rotation Error with clean 2D points: 1.8762051289256414e-12
Translation Error with clean 2D points: 2.2711930521517543
Intrinsic Error with noisy 2D points: 0.7215816824301863
Rotation Error with noisy 2D points: 3.4630792427325425
Translation Error with noisy 2D points: 3.1938223919113424


* **In your write-up**: Please include the output of this script in your PDF.

#### 2.3 - Projecting CAD Models to 2D (BONUS)
---
Now you will utilize what you have implemented to estimate the camera matrix from a real image, shown in Figure 5 (left), and project the 3D object (CAD model), shown in Figure 5 (right), back on to the image plane. 

<center> <img src = "/Users/yiftachedelstain/ee046746-computer-vision-private/HW/hw4_structure_from_motion/assets/airplane_image_CAD.jpg" style="width:75%">
<center> Figure 5 - The provided image and 3D CAD model.

Write a script that does the following:
* Load an image `image`, a CAD model `cad`, 2D points `x` and 3D points `X` from the data file `data/pnp.npz`.
* Run `estimate_pose` and `estimate_params` to estimate camera matrix $M$, intrinsic matrix $K$, rotation matrix $R$, and translation $t$.
* Use your estimated camera matrix $M$ to project the given 3D points $P$ onto the image.
* Plot the given 2D points $p$ and the projected 3D points on screen. An example is shown in Figure 6 (left).
* Draw the CAD model rotated by your estimated rotation $R$ on screen. An example is shown in Figure 6 (middle).
* Project the CAD's all vertices onto the image and draw the projected CAD model overlapping with the 2D image. An example is shown in Figure 6 (right).
* **In your write-up**: Please include the three images similar to Figure 6 in your PDF. You must use different colors from Figure 6. For example, green circle for given 2D points, black points for projected 3D points, blue CAD model, and red projected CAD model overlapping on the image. You will get **NO credit** if you use the same color.

In [108]:
# 1. Load the data from the file
data_content = np.load("../data/pnp.npz", allow_pickle=True)
image_data, cad_model, points_2d, points_3d = data_content['image'], data_content['cad'], data_content['x'], data_content['X']

# 2. Estimate the camera matrix and parameters
camera_matrix = estimate_pose(points_2d, points_3d)
intrinsic_matrix, rotation_matrix, translation_vector = estimate_params(camera_matrix)

# 3. Project the 3D points onto the 2D image plane using the camera matrix
homogeneous_3d_points = np.hstack((points_3d, np.ones((points_3d.shape[0], 1))))
projected_points = camera_matrix @ homogeneous_3d_points.T
projected_points /= projected_points[2, :]
projected_points_2d = projected_points[:2, :].T

# 4. Visualize the original 2D points and projected 3D points
plt.imshow(image_data)
plt.scatter(projected_points_2d[:, 0], projected_points_2d[:, 1], c='b', marker='x')

# Draw circles around the given 2D points
for coord in points_2d:
    circle_patch = patches.Circle((coord[0], coord[1]), radius=10, edgecolor='r', facecolor='none')
    plt.gca().add_patch(circle_patch)

plt.legend(['Projected 3D Points', 'Given 2D Points'])
plt.show()

In [ ]:
# 5. Rotate and display the CAD model using the estimated rotation matrix
cad_vertices = cad_model[0, 0][0]
cad_faces = cad_model[0, 0][1]
rotated_cad = (rotation_matrix @ cad_vertices.T).T

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_trisurf(rotated_cad[:, 0], rotated_cad[:, 1], rotated_cad[:, 2], triangles=cad_faces - 1, linewidth=0.1, edgecolor='blue')
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
plt.title('Rotated CAD Model')
plt.show()

In [ ]:
# 6. Project CAD vertices onto the image and overlay the projected model
homogeneous_cad_vertices = np.hstack((cad_vertices, np.ones((cad_vertices.shape[0], 1))))
projected_cad_vertices = camera_matrix @ homogeneous_cad_vertices.T
projected_cad_vertices /= projected_cad_vertices[2, :]
projected_cad_2d = projected_cad_vertices[:2, :].T

fig = plt.figure()
ax = fig.add_subplot(111)
ax.imshow(image_data)
ax.triplot(projected_cad_2d[:, 0], projected_cad_2d[:, 1], cad_faces - 1, alpha=0.8, color='green')
ax.set_xlabel('X')
ax.set_ylabel('Y')
plt.title('CAD Vertices Projected')
plt.show()

* Example result:

<center> <img src = "../assets/airplane_projection.jpg" style="width:100%">
<center> Figure 6 - Project a CAD model back onto the image. Left: the image annotated with given 2D points (blue circle) and projected 3D points (red points); Middle: the CAD model rotated by estimated R; Right: the image overlapping with
projected CAD model.

## <img src="https://img.icons8.com/dusk/64/000000/prize.png" style="height:50px;display:inline"> References & Credits
* Carnegie Mellon University - CMU
* Icons from <a href="https://icons8.com/">Icon8.com</a> - https://icons8.com
